2025-05-18 22:41:28 [ERROR] uncaughtException: Unexpected identifier 'branch_auth'
Z:\Visual_Codes\jagya_const\backend\models\authModels\branch\index.js:43
      UPDATE branch_auth SET br_r_id = ?, br_user_id = ?, br_password = ? WHERE br_a_id = ?
             ^^^^^^^^^^^

SyntaxError: Unexpected identifier 'branch_auth'
    at wrapSafe (node:internal/modules/cjs/loader:1469:18)
    at Module._compile (node:internal/modules/cjs/loader:1491:20)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\jagya_const\backend\controllers\authControllers\branch\index.js:5:21)
Z:\Visual_Codes\jagya_const\backend\models\authModels\branch\index.js:43
      UPDATE branch_auth SET br_r_id = ?, br_user_id = ?, br_password = ? WHERE br_a_id = ?
             ^^^^^^^^^^^

SyntaxError: Unexpected identifier 'branch_auth'
    at wrapSafe (node:internal/modules/cjs/loader:1469:18)
    at Module._compile (node:internal/modules/cjs/loader:1491:20)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\jagya_const\backend\controllers\authControllers\branch\index.js:5:21)
{
  error: Z:\Visual_Codes\jagya_const\backend\models\authModels\branch\index.js:43
        UPDATE branch_auth SET br_r_id = ?, br_user_id = ?, br_password = ? WHERE br_a_id = ?
               ^^^^^^^^^^^
  
  SyntaxError: Unexpected identifier 'branch_auth'
      at wrapSafe (node:internal/modules/cjs/loader:1469:18)
      at Module._compile (node:internal/modules/cjs/loader:1491:20)
      at Object..js (node:internal/modules/cjs/loader:1689:10)
      at Module.load (node:internal/modules/cjs/loader:1318:32)
      at Function._load (node:internal/modules/cjs/loader:1128:12)
      at TracingChannel.traceSync (node:diagnostics_channel:315:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
      at Module.require (node:internal/modules/cjs/loader:1340:12)
      at require (node:internal/modules/helpers:141:16)
      at Object.<anonymous> (Z:\Visual_Codes\jagya_const\backend\controllers\authControllers\branch\index.js:5:21),
  exception: true,
  date: 'Sun May 18 2025 22:41:28 GMT+0530 (India Standard Time)',
  process: {
    pid: 9420,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\jagya_const\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\jagya_const\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 104206336,
      heapTotal: 70172672,
      heapUsed: 50300224,
      external: 2318336,
      arrayBuffers: 21664
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 962990.968 },
  trace: [
    {
      column: 18,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapSafe',
      line: 1469,
      method: null,
      native: false
    },
    {
      column: 20,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module._compile',
      line: 1491,
      method: '_compile',
      native: false
    },
    {
      column: 10,
      file: 'node:internal/modules/cjs/loader',
      function: 'Object..js',
      line: 1689,
      method: '.js',
      native: false
    },
    {
      column: 32,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.load',
      line: 1318,
      method: 'load',
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Function._load',
      line: 1128,
      method: '_load',
      native: false
    },
    {
      column: 14,
      file: 'node:diagnostics_channel',
      function: 'TracingChannel.traceSync',
      line: 315,
      method: 'traceSync',
      native: false
    },
    {
      column: 24,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapModuleLoad',
      line: 218,
      method: null,
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.require',
      line: 1340,
      method: 'require',
      native: false
    },
    {
      column: 16,
      file: 'node:internal/modules/helpers',
      function: 'require',
      line: 141,
      method: null,
      native: false
    },
    {
      column: 21,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\controllers\\authControllers\\branch\\index.js',
      function: null,
      line: 5,
      method: null,
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
2025-05-29 16:36:10 [ERROR] uncaughtException: Access denied for user 'reynrel01'@'localhost' (using password: YES)
Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
    at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
    at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
    at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
    at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
{
  error: Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
      at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
      at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5) {
    code: 'ER_ACCESS_DENIED_ERROR',
    errno: 1045,
    sqlState: '28000',
    sqlMessage: "Access denied for user 'reynrel01'@'localhost' (using password: YES)",
    sql: undefined
  },
  exception: true,
  date: 'Thu May 29 2025 16:36:10 GMT+0530 (India Standard Time)',
  process: {
    pid: 13208,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\jagya_const\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\jagya_const\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 105512960,
      heapTotal: 71245824,
      heapUsed: 40578392,
      external: 2346683,
      arrayBuffers: 29583
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 8352.671 },
  trace: [
    {
      column: 17,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\packets\\packet.js',
      function: 'Packet.asError',
      line: 740,
      method: 'asError',
      native: false
    },
    {
      column: 26,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\commands\\command.js',
      function: 'ClientHandshake.execute',
      line: 29,
      method: 'execute',
      native: false
    },
    {
      column: 34,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: 'PoolConnection.handlePacket',
      line: 475,
      method: 'handlePacket',
      native: false
    },
    {
      column: 12,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: 'PacketParser.onPacket',
      line: 93,
      method: 'onPacket',
      native: false
    },
    {
      column: 16,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\packet_parser.js',
      function: 'PacketParser.executeStart',
      line: 75,
      method: 'executeStart',
      native: false
    },
    {
      column: 25,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: null,
      line: 100,
      method: null,
      native: false
    },
    {
      column: 28,
      file: 'node:events',
      function: 'Socket.emit',
      line: 518,
      method: 'emit',
      native: false
    },
    {
      column: 12,
      file: 'node:internal/streams/readable',
      function: 'addChunk',
      line: 561,
      method: null,
      native: false
    },
    {
      column: 3,
      file: 'node:internal/streams/readable',
      function: 'readableAddChunkPushByteMode',
      line: 512,
      method: null,
      native: false
    },
    {
      column: 5,
      file: 'node:internal/streams/readable',
      function: 'Readable.push',
      line: 392,
      method: 'push',
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
2025-05-29 16:38:41 [ERROR] uncaughtException: Access denied for user 'reynrel01'@'localhost' (using password: YES)
Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
    at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
    at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
    at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
    at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
{
  error: Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
      at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
      at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5) {
    code: 'ER_ACCESS_DENIED_ERROR',
    errno: 1045,
    sqlState: '28000',
    sqlMessage: "Access denied for user 'reynrel01'@'localhost' (using password: YES)",
    sql: undefined
  },
  exception: true,
  date: 'Thu May 29 2025 16:38:41 GMT+0530 (India Standard Time)',
  process: {
    pid: 8308,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\jagya_const\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\jagya_const\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 106467328,
      heapTotal: 72384512,
      heapUsed: 41416504,
      external: 2346681,
      arrayBuffers: 29581
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 8504.546 },
  trace: [
    {
      column: 17,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\packets\\packet.js',
      function: 'Packet.asError',
      line: 740,
      method: 'asError',
      native: false
    },
    {
      column: 26,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\commands\\command.js',
      function: 'ClientHandshake.execute',
      line: 29,
      method: 'execute',
      native: false
    },
    {
      column: 34,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: 'PoolConnection.handlePacket',
      line: 475,
      method: 'handlePacket',
      native: false
    },
    {
      column: 12,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: 'PacketParser.onPacket',
      line: 93,
      method: 'onPacket',
      native: false
    },
    {
      column: 16,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\packet_parser.js',
      function: 'PacketParser.executeStart',
      line: 75,
      method: 'executeStart',
      native: false
    },
    {
      column: 25,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: null,
      line: 100,
      method: null,
      native: false
    },
    {
      column: 28,
      file: 'node:events',
      function: 'Socket.emit',
      line: 518,
      method: 'emit',
      native: false
    },
    {
      column: 12,
      file: 'node:internal/streams/readable',
      function: 'addChunk',
      line: 561,
      method: null,
      native: false
    },
    {
      column: 3,
      file: 'node:internal/streams/readable',
      function: 'readableAddChunkPushByteMode',
      line: 512,
      method: null,
      native: false
    },
    {
      column: 5,
      file: 'node:internal/streams/readable',
      function: 'Readable.push',
      line: 392,
      method: 'push',
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
2025-05-29 16:39:11 [ERROR] uncaughtException: Access denied for user 'reynrel01'@'localhost' (using password: YES)
Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
    at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
    at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
    at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
    at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
{
  error: Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
      at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
      at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5) {
    code: 'ER_ACCESS_DENIED_ERROR',
    errno: 1045,
    sqlState: '28000',
    sqlMessage: "Access denied for user 'reynrel01'@'localhost' (using password: YES)",
    sql: undefined
  },
  exception: true,
  date: 'Thu May 29 2025 16:39:11 GMT+0530 (India Standard Time)',
  process: {
    pid: 5536,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\jagya_const\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\jagya_const\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 106512384,
      heapTotal: 72441856,
      heapUsed: 41436816,
      external: 2346681,
      arrayBuffers: 29581
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 8534.625 },
  trace: [
    {
      column: 17,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\packets\\packet.js',
      function: 'Packet.asError',
      line: 740,
      method: 'asError',
      native: false
    },
    {
      column: 26,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\commands\\command.js',
      function: 'ClientHandshake.execute',
      line: 29,
      method: 'execute',
      native: false
    },
    {
      column: 34,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: 'PoolConnection.handlePacket',
      line: 475,
      method: 'handlePacket',
      native: false
    },
    {
      column: 12,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: 'PacketParser.onPacket',
      line: 93,
      method: 'onPacket',
      native: false
    },
    {
      column: 16,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\packet_parser.js',
      function: 'PacketParser.executeStart',
      line: 75,
      method: 'executeStart',
      native: false
    },
    {
      column: 25,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: null,
      line: 100,
      method: null,
      native: false
    },
    {
      column: 28,
      file: 'node:events',
      function: 'Socket.emit',
      line: 518,
      method: 'emit',
      native: false
    },
    {
      column: 12,
      file: 'node:internal/streams/readable',
      function: 'addChunk',
      line: 561,
      method: null,
      native: false
    },
    {
      column: 3,
      file: 'node:internal/streams/readable',
      function: 'readableAddChunkPushByteMode',
      line: 512,
      method: null,
      native: false
    },
    {
      column: 5,
      file: 'node:internal/streams/readable',
      function: 'Readable.push',
      line: 392,
      method: 'push',
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
2025-05-29 16:42:04 [ERROR] uncaughtException: Access denied for user 'reynrel01'@'localhost' (using password: YES)
Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
    at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
    at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
    at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
    at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
{
  error: Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
      at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
      at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5) {
    code: 'ER_ACCESS_DENIED_ERROR',
    errno: 1045,
    sqlState: '28000',
    sqlMessage: "Access denied for user 'reynrel01'@'localhost' (using password: YES)",
    sql: undefined
  },
  exception: true,
  date: 'Thu May 29 2025 16:42:04 GMT+0530 (India Standard Time)',
  process: {
    pid: 10928,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\jagya_const\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\jagya_const\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 106029056,
      heapTotal: 71974912,
      heapUsed: 41129600,
      external: 2346683,
      arrayBuffers: 29583
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 8707.015 },
  trace: [
    {
      column: 17,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\packets\\packet.js',
      function: 'Packet.asError',
      line: 740,
      method: 'asError',
      native: false
    },
    {
      column: 26,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\commands\\command.js',
      function: 'ClientHandshake.execute',
      line: 29,
      method: 'execute',
      native: false
    },
    {
      column: 34,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: 'PoolConnection.handlePacket',
      line: 475,
      method: 'handlePacket',
      native: false
    },
    {
      column: 12,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: 'PacketParser.onPacket',
      line: 93,
      method: 'onPacket',
      native: false
    },
    {
      column: 16,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\packet_parser.js',
      function: 'PacketParser.executeStart',
      line: 75,
      method: 'executeStart',
      native: false
    },
    {
      column: 25,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: null,
      line: 100,
      method: null,
      native: false
    },
    {
      column: 28,
      file: 'node:events',
      function: 'Socket.emit',
      line: 518,
      method: 'emit',
      native: false
    },
    {
      column: 12,
      file: 'node:internal/streams/readable',
      function: 'addChunk',
      line: 561,
      method: null,
      native: false
    },
    {
      column: 3,
      file: 'node:internal/streams/readable',
      function: 'readableAddChunkPushByteMode',
      line: 512,
      method: null,
      native: false
    },
    {
      column: 5,
      file: 'node:internal/streams/readable',
      function: 'Readable.push',
      line: 392,
      method: 'push',
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
2025-05-29 16:42:11 [ERROR] uncaughtException: Access denied for user 'reynrel01'@'localhost' (using password: YES)
Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
    at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
    at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
    at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
    at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
{
  error: Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
      at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
      at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5) {
    code: 'ER_ACCESS_DENIED_ERROR',
    errno: 1045,
    sqlState: '28000',
    sqlMessage: "Access denied for user 'reynrel01'@'localhost' (using password: YES)",
    sql: undefined
  },
  exception: true,
  date: 'Thu May 29 2025 16:42:11 GMT+0530 (India Standard Time)',
  process: {
    pid: 12688,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\jagya_const\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\jagya_const\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 107208704,
      heapTotal: 72908800,
      heapUsed: 42250248,
      external: 2346683,
      arrayBuffers: 29583
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 8714.109 },
  trace: [
    {
      column: 17,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\packets\\packet.js',
      function: 'Packet.asError',
      line: 740,
      method: 'asError',
      native: false
    },
    {
      column: 26,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\commands\\command.js',
      function: 'ClientHandshake.execute',
      line: 29,
      method: 'execute',
      native: false
    },
    {
      column: 34,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: 'PoolConnection.handlePacket',
      line: 475,
      method: 'handlePacket',
      native: false
    },
    {
      column: 12,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: 'PacketParser.onPacket',
      line: 93,
      method: 'onPacket',
      native: false
    },
    {
      column: 16,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\packet_parser.js',
      function: 'PacketParser.executeStart',
      line: 75,
      method: 'executeStart',
      native: false
    },
    {
      column: 25,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: null,
      line: 100,
      method: null,
      native: false
    },
    {
      column: 28,
      file: 'node:events',
      function: 'Socket.emit',
      line: 518,
      method: 'emit',
      native: false
    },
    {
      column: 12,
      file: 'node:internal/streams/readable',
      function: 'addChunk',
      line: 561,
      method: null,
      native: false
    },
    {
      column: 3,
      file: 'node:internal/streams/readable',
      function: 'readableAddChunkPushByteMode',
      line: 512,
      method: null,
      native: false
    },
    {
      column: 5,
      file: 'node:internal/streams/readable',
      function: 'Readable.push',
      line: 392,
      method: 'push',
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
2025-05-29 16:42:15 [ERROR] uncaughtException: Access denied for user 'reynrel01'@'localhost' (using password: YES)
Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
    at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
    at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
    at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
    at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
{
  error: Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
      at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
      at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5) {
    code: 'ER_ACCESS_DENIED_ERROR',
    errno: 1045,
    sqlState: '28000',
    sqlMessage: "Access denied for user 'reynrel01'@'localhost' (using password: YES)",
    sql: undefined
  },
  exception: true,
  date: 'Thu May 29 2025 16:42:15 GMT+0530 (India Standard Time)',
  process: {
    pid: 8964,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\jagya_const\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\jagya_const\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 105529344,
      heapTotal: 71450624,
      heapUsed: 40723000,
      external: 2346681,
      arrayBuffers: 29581
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 8718.609 },
  trace: [
    {
      column: 17,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\packets\\packet.js',
      function: 'Packet.asError',
      line: 740,
      method: 'asError',
      native: false
    },
    {
      column: 26,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\commands\\command.js',
      function: 'ClientHandshake.execute',
      line: 29,
      method: 'execute',
      native: false
    },
    {
      column: 34,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: 'PoolConnection.handlePacket',
      line: 475,
      method: 'handlePacket',
      native: false
    },
    {
      column: 12,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: 'PacketParser.onPacket',
      line: 93,
      method: 'onPacket',
      native: false
    },
    {
      column: 16,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\packet_parser.js',
      function: 'PacketParser.executeStart',
      line: 75,
      method: 'executeStart',
      native: false
    },
    {
      column: 25,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: null,
      line: 100,
      method: null,
      native: false
    },
    {
      column: 28,
      file: 'node:events',
      function: 'Socket.emit',
      line: 518,
      method: 'emit',
      native: false
    },
    {
      column: 12,
      file: 'node:internal/streams/readable',
      function: 'addChunk',
      line: 561,
      method: null,
      native: false
    },
    {
      column: 3,
      file: 'node:internal/streams/readable',
      function: 'readableAddChunkPushByteMode',
      line: 512,
      method: null,
      native: false
    },
    {
      column: 5,
      file: 'node:internal/streams/readable',
      function: 'Readable.push',
      line: 392,
      method: 'push',
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
2025-05-29 16:42:48 [ERROR] uncaughtException: Access denied for user 'reynrel01'@'localhost' (using password: YES)
Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
    at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
    at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
    at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
    at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
{
  error: Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
      at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
      at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5) {
    code: 'ER_ACCESS_DENIED_ERROR',
    errno: 1045,
    sqlState: '28000',
    sqlMessage: "Access denied for user 'reynrel01'@'localhost' (using password: YES)",
    sql: undefined
  },
  exception: true,
  date: 'Thu May 29 2025 16:42:48 GMT+0530 (India Standard Time)',
  process: {
    pid: 10592,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\jagya_const\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\jagya_const\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 106438656,
      heapTotal: 72499200,
      heapUsed: 41305704,
      external: 2346683,
      arrayBuffers: 29583
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 8750.781 },
  trace: [
    {
      column: 17,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\packets\\packet.js',
      function: 'Packet.asError',
      line: 740,
      method: 'asError',
      native: false
    },
    {
      column: 26,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\commands\\command.js',
      function: 'ClientHandshake.execute',
      line: 29,
      method: 'execute',
      native: false
    },
    {
      column: 34,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: 'PoolConnection.handlePacket',
      line: 475,
      method: 'handlePacket',
      native: false
    },
    {
      column: 12,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: 'PacketParser.onPacket',
      line: 93,
      method: 'onPacket',
      native: false
    },
    {
      column: 16,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\packet_parser.js',
      function: 'PacketParser.executeStart',
      line: 75,
      method: 'executeStart',
      native: false
    },
    {
      column: 25,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: null,
      line: 100,
      method: null,
      native: false
    },
    {
      column: 28,
      file: 'node:events',
      function: 'Socket.emit',
      line: 518,
      method: 'emit',
      native: false
    },
    {
      column: 12,
      file: 'node:internal/streams/readable',
      function: 'addChunk',
      line: 561,
      method: null,
      native: false
    },
    {
      column: 3,
      file: 'node:internal/streams/readable',
      function: 'readableAddChunkPushByteMode',
      line: 512,
      method: null,
      native: false
    },
    {
      column: 5,
      file: 'node:internal/streams/readable',
      function: 'Readable.push',
      line: 392,
      method: 'push',
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
2025-05-29 16:42:51 [ERROR] uncaughtException: Access denied for user 'reynrel01'@'localhost' (using password: YES)
Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
    at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
    at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
    at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
    at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
{
  error: Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
      at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
      at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5) {
    code: 'ER_ACCESS_DENIED_ERROR',
    errno: 1045,
    sqlState: '28000',
    sqlMessage: "Access denied for user 'reynrel01'@'localhost' (using password: YES)",
    sql: undefined
  },
  exception: true,
  date: 'Thu May 29 2025 16:42:51 GMT+0530 (India Standard Time)',
  process: {
    pid: 9148,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\jagya_const\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\jagya_const\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 106708992,
      heapTotal: 72556544,
      heapUsed: 41241312,
      external: 2346681,
      arrayBuffers: 29581
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 8753.703 },
  trace: [
    {
      column: 17,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\packets\\packet.js',
      function: 'Packet.asError',
      line: 740,
      method: 'asError',
      native: false
    },
    {
      column: 26,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\commands\\command.js',
      function: 'ClientHandshake.execute',
      line: 29,
      method: 'execute',
      native: false
    },
    {
      column: 34,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: 'PoolConnection.handlePacket',
      line: 475,
      method: 'handlePacket',
      native: false
    },
    {
      column: 12,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: 'PacketParser.onPacket',
      line: 93,
      method: 'onPacket',
      native: false
    },
    {
      column: 16,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\packet_parser.js',
      function: 'PacketParser.executeStart',
      line: 75,
      method: 'executeStart',
      native: false
    },
    {
      column: 25,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: null,
      line: 100,
      method: null,
      native: false
    },
    {
      column: 28,
      file: 'node:events',
      function: 'Socket.emit',
      line: 518,
      method: 'emit',
      native: false
    },
    {
      column: 12,
      file: 'node:internal/streams/readable',
      function: 'addChunk',
      line: 561,
      method: null,
      native: false
    },
    {
      column: 3,
      file: 'node:internal/streams/readable',
      function: 'readableAddChunkPushByteMode',
      line: 512,
      method: null,
      native: false
    },
    {
      column: 5,
      file: 'node:internal/streams/readable',
      function: 'Readable.push',
      line: 392,
      method: 'push',
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
2025-05-29 16:43:36 [ERROR] uncaughtException: Access denied for user 'reynrel01'@'localhost' (using password: YES)
Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
    at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
    at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
    at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
    at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
{
  error: Error: Access denied for user 'reynrel01'@'localhost' (using password: YES)
      at Packet.asError (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packets\packet.js:740:17)
      at ClientHandshake.execute (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at PoolConnection.handlePacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (Z:\Visual_Codes\jagya_const\backend\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5) {
    code: 'ER_ACCESS_DENIED_ERROR',
    errno: 1045,
    sqlState: '28000',
    sqlMessage: "Access denied for user 'reynrel01'@'localhost' (using password: YES)",
    sql: undefined
  },
  exception: true,
  date: 'Thu May 29 2025 16:43:36 GMT+0530 (India Standard Time)',
  process: {
    pid: 10164,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\jagya_const\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\jagya_const\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 106201088,
      heapTotal: 71770112,
      heapUsed: 41106080,
      external: 2346683,
      arrayBuffers: 29583
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 8799.453 },
  trace: [
    {
      column: 17,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\packets\\packet.js',
      function: 'Packet.asError',
      line: 740,
      method: 'asError',
      native: false
    },
    {
      column: 26,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\commands\\command.js',
      function: 'ClientHandshake.execute',
      line: 29,
      method: 'execute',
      native: false
    },
    {
      column: 34,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: 'PoolConnection.handlePacket',
      line: 475,
      method: 'handlePacket',
      native: false
    },
    {
      column: 12,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: 'PacketParser.onPacket',
      line: 93,
      method: 'onPacket',
      native: false
    },
    {
      column: 16,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\packet_parser.js',
      function: 'PacketParser.executeStart',
      line: 75,
      method: 'executeStart',
      native: false
    },
    {
      column: 25,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\node_modules\\mysql2\\lib\\base\\connection.js',
      function: null,
      line: 100,
      method: null,
      native: false
    },
    {
      column: 28,
      file: 'node:events',
      function: 'Socket.emit',
      line: 518,
      method: 'emit',
      native: false
    },
    {
      column: 12,
      file: 'node:internal/streams/readable',
      function: 'addChunk',
      line: 561,
      method: null,
      native: false
    },
    {
      column: 3,
      file: 'node:internal/streams/readable',
      function: 'readableAddChunkPushByteMode',
      line: 512,
      method: null,
      native: false
    },
    {
      column: 5,
      file: 'node:internal/streams/readable',
      function: 'Readable.push',
      line: 392,
      method: 'push',
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
2025-06-23 19:10:14 [ERROR] uncaughtException: print is not defined
ReferenceError: print is not defined
    at Object.<anonymous> (Z:\Visual_Codes\jagya_const\backend\app.js:61:27)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49
ReferenceError: print is not defined
    at Object.<anonymous> (Z:\Visual_Codes\jagya_const\backend\app.js:61:27)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49
{
  error: ReferenceError: print is not defined
      at Object.<anonymous> (Z:\Visual_Codes\jagya_const\backend\app.js:61:27)
      at Module._compile (node:internal/modules/cjs/loader:1546:14)
      at Object..js (node:internal/modules/cjs/loader:1689:10)
      at Module.load (node:internal/modules/cjs/loader:1318:32)
      at Function._load (node:internal/modules/cjs/loader:1128:12)
      at TracingChannel.traceSync (node:diagnostics_channel:315:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
      at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
      at node:internal/main/run_main_module:36:49,
  exception: true,
  date: 'Mon Jun 23 2025 19:10:14 GMT+0530 (India Standard Time)',
  process: {
    pid: 9372,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\jagya_const\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\jagya_const\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 106807296,
      heapTotal: 69672960,
      heapUsed: 49206984,
      external: 2318336,
      arrayBuffers: 21664
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 200209.265 },
  trace: [
    {
      column: 27,
      file: 'Z:\\Visual_Codes\\jagya_const\\backend\\app.js',
      function: null,
      line: 61,
      method: null,
      native: false
    },
    {
      column: 14,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module._compile',
      line: 1546,
      method: '_compile',
      native: false
    },
    {
      column: 10,
      file: 'node:internal/modules/cjs/loader',
      function: 'Object..js',
      line: 1689,
      method: '.js',
      native: false
    },
    {
      column: 32,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.load',
      line: 1318,
      method: 'load',
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Function._load',
      line: 1128,
      method: '_load',
      native: false
    },
    {
      column: 14,
      file: 'node:diagnostics_channel',
      function: 'TracingChannel.traceSync',
      line: 315,
      method: 'traceSync',
      native: false
    },
    {
      column: 24,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapModuleLoad',
      line: 218,
      method: null,
      native: false
    },
    {
      column: 5,
      file: 'node:internal/modules/run_main',
      function: 'Function.executeUserEntryPoint [as runMain]',
      line: 170,
      method: 'executeUserEntryPoint [as runMain]',
      native: false
    },
    {
      column: 49,
      file: 'node:internal/main/run_main_module',
      function: null,
      line: 36,
      method: null,
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
2025-07-01 12:17:08 [ERROR] uncaughtException: Cannot find module 'Z:\Visual_Codes\rudrax\backend\models\authMclsodels\admin'
Require stack:
- Z:\Visual_Codes\rudrax\backend\controllers\authControllers\admin\index.js
- Z:\Visual_Codes\rudrax\backend\routers\authApi.js
- Z:\Visual_Codes\rudrax\backend\app.js
Error: Cannot find module 'Z:\Visual_Codes\rudrax\backend\models\authMclsodels\admin'
Require stack:
- Z:\Visual_Codes\rudrax\backend\controllers\authControllers\admin\index.js
- Z:\Visual_Codes\rudrax\backend\routers\authApi.js
- Z:\Visual_Codes\rudrax\backend\app.js
    at Function.<anonymous> (node:internal/modules/cjs/loader:1249:15)
    at Module._resolveFilename (Z:\Visual_Codes\rudrax\backend\node_modules\module-alias\index.js:49:29)
    at Function._load (node:internal/modules/cjs/loader:1075:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\controllers\authControllers\admin\index.js:5:25)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
Error: Cannot find module 'Z:\Visual_Codes\rudrax\backend\models\authMclsodels\admin'
Require stack:
- Z:\Visual_Codes\rudrax\backend\controllers\authControllers\admin\index.js
- Z:\Visual_Codes\rudrax\backend\routers\authApi.js
- Z:\Visual_Codes\rudrax\backend\app.js
    at Function.<anonymous> (node:internal/modules/cjs/loader:1249:15)
    at Module._resolveFilename (Z:\Visual_Codes\rudrax\backend\node_modules\module-alias\index.js:49:29)
    at Function._load (node:internal/modules/cjs/loader:1075:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\controllers\authControllers\admin\index.js:5:25)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
{
  error: Error: Cannot find module 'Z:\Visual_Codes\rudrax\backend\models\authMclsodels\admin'
  Require stack:
  - Z:\Visual_Codes\rudrax\backend\controllers\authControllers\admin\index.js
  - Z:\Visual_Codes\rudrax\backend\routers\authApi.js
  - Z:\Visual_Codes\rudrax\backend\app.js
      at Function.<anonymous> (node:internal/modules/cjs/loader:1249:15)
      at Module._resolveFilename (Z:\Visual_Codes\rudrax\backend\node_modules\module-alias\index.js:49:29)
      at Function._load (node:internal/modules/cjs/loader:1075:27)
      at TracingChannel.traceSync (node:diagnostics_channel:315:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
      at Module.require (node:internal/modules/cjs/loader:1340:12)
      at require (node:internal/modules/helpers:141:16)
      at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\controllers\authControllers\admin\index.js:5:25)
      at Module._compile (node:internal/modules/cjs/loader:1546:14)
      at Object..js (node:internal/modules/cjs/loader:1689:10) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      'Z:\\Visual_Codes\\rudrax\\backend\\controllers\\authControllers\\admin\\index.js',
      'Z:\\Visual_Codes\\rudrax\\backend\\routers\\authApi.js',
      'Z:\\Visual_Codes\\rudrax\\backend\\app.js'
    ]
  },
  exception: true,
  date: 'Tue Jul 01 2025 12:17:08 GMT+0530 (India Standard Time)',
  process: {
    pid: 9100,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\rudrax\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\rudrax\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 105160704,
      heapTotal: 68624384,
      heapUsed: 47570360,
      external: 2318336,
      arrayBuffers: 21664
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 51277.093 },
  trace: [
    {
      column: 15,
      file: 'node:internal/modules/cjs/loader',
      function: null,
      line: 1249,
      method: null,
      native: false
    },
    {
      column: 29,
      file: 'Z:\\Visual_Codes\\rudrax\\backend\\node_modules\\module-alias\\index.js',
      function: 'Module._resolveFilename',
      line: 49,
      method: '_resolveFilename',
      native: false
    },
    {
      column: 27,
      file: 'node:internal/modules/cjs/loader',
      function: 'Function._load',
      line: 1075,
      method: '_load',
      native: false
    },
    {
      column: 14,
      file: 'node:diagnostics_channel',
      function: 'TracingChannel.traceSync',
      line: 315,
      method: 'traceSync',
      native: false
    },
    {
      column: 24,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapModuleLoad',
      line: 218,
      method: null,
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.require',
      line: 1340,
      method: 'require',
      native: false
    },
    {
      column: 16,
      file: 'node:internal/modules/helpers',
      function: 'require',
      line: 141,
      method: null,
      native: false
    },
    {
      column: 25,
      file: 'Z:\\Visual_Codes\\rudrax\\backend\\controllers\\authControllers\\admin\\index.js',
      function: null,
      line: 5,
      method: null,
      native: false
    },
    {
      column: 14,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module._compile',
      line: 1546,
      method: '_compile',
      native: false
    },
    {
      column: 10,
      file: 'node:internal/modules/cjs/loader',
      function: 'Object..js',
      line: 1689,
      method: '.js',
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
2025-07-01 12:18:18 [ERROR] uncaughtException: aminControllers is not defined
ReferenceError: aminControllers is not defined
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\routers\authApi.js:8:13)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:20)
ReferenceError: aminControllers is not defined
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\routers\authApi.js:8:13)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:20)
{
  error: ReferenceError: aminControllers is not defined
      at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\routers\authApi.js:8:13)
      at Module._compile (node:internal/modules/cjs/loader:1546:14)
      at Object..js (node:internal/modules/cjs/loader:1689:10)
      at Module.load (node:internal/modules/cjs/loader:1318:32)
      at Function._load (node:internal/modules/cjs/loader:1128:12)
      at TracingChannel.traceSync (node:diagnostics_channel:315:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
      at Module.require (node:internal/modules/cjs/loader:1340:12)
      at require (node:internal/modules/helpers:141:16)
      at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:20),
  exception: true,
  date: 'Tue Jul 01 2025 12:18:18 GMT+0530 (India Standard Time)',
  process: {
    pid: 3788,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\rudrax\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\rudrax\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 107290624,
      heapTotal: 69410816,
      heapUsed: 48123120,
      external: 2318336,
      arrayBuffers: 21664
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 51346.75 },
  trace: [
    {
      column: 13,
      file: 'Z:\\Visual_Codes\\rudrax\\backend\\routers\\authApi.js',
      function: null,
      line: 8,
      method: null,
      native: false
    },
    {
      column: 14,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module._compile',
      line: 1546,
      method: '_compile',
      native: false
    },
    {
      column: 10,
      file: 'node:internal/modules/cjs/loader',
      function: 'Object..js',
      line: 1689,
      method: '.js',
      native: false
    },
    {
      column: 32,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.load',
      line: 1318,
      method: 'load',
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Function._load',
      line: 1128,
      method: '_load',
      native: false
    },
    {
      column: 14,
      file: 'node:diagnostics_channel',
      function: 'TracingChannel.traceSync',
      line: 315,
      method: 'traceSync',
      native: false
    },
    {
      column: 24,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapModuleLoad',
      line: 218,
      method: null,
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.require',
      line: 1340,
      method: 'require',
      native: false
    },
    {
      column: 16,
      file: 'node:internal/modules/helpers',
      function: 'require',
      line: 141,
      method: null,
      native: false
    },
    {
      column: 20,
      file: 'Z:\\Visual_Codes\\rudrax\\backend\\app.js',
      function: null,
      line: 43,
      method: null,
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
2025-07-01 12:26:39 [ERROR] uncaughtException: aminControllers is not defined
ReferenceError: aminControllers is not defined
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\routers\authApi.js:8:13)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:20)
ReferenceError: aminControllers is not defined
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\routers\authApi.js:8:13)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:20)
{
  error: ReferenceError: aminControllers is not defined
      at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\routers\authApi.js:8:13)
      at Module._compile (node:internal/modules/cjs/loader:1546:14)
      at Object..js (node:internal/modules/cjs/loader:1689:10)
      at Module.load (node:internal/modules/cjs/loader:1318:32)
      at Function._load (node:internal/modules/cjs/loader:1128:12)
      at TracingChannel.traceSync (node:diagnostics_channel:315:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
      at Module.require (node:internal/modules/cjs/loader:1340:12)
      at require (node:internal/modules/helpers:141:16)
      at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:20),
  exception: true,
  date: 'Tue Jul 01 2025 12:26:39 GMT+0530 (India Standard Time)',
  process: {
    pid: 3336,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\rudrax\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\rudrax\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 104931328,
      heapTotal: 68886528,
      heapUsed: 47679408,
      external: 2318336,
      arrayBuffers: 21664
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 51848.14 },
  trace: [
    {
      column: 13,
      file: 'Z:\\Visual_Codes\\rudrax\\backend\\routers\\authApi.js',
      function: null,
      line: 8,
      method: null,
      native: false
    },
    {
      column: 14,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module._compile',
      line: 1546,
      method: '_compile',
      native: false
    },
    {
      column: 10,
      file: 'node:internal/modules/cjs/loader',
      function: 'Object..js',
      line: 1689,
      method: '.js',
      native: false
    },
    {
      column: 32,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.load',
      line: 1318,
      method: 'load',
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Function._load',
      line: 1128,
      method: '_load',
      native: false
    },
    {
      column: 14,
      file: 'node:diagnostics_channel',
      function: 'TracingChannel.traceSync',
      line: 315,
      method: 'traceSync',
      native: false
    },
    {
      column: 24,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapModuleLoad',
      line: 218,
      method: null,
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.require',
      line: 1340,
      method: 'require',
      native: false
    },
    {
      column: 16,
      file: 'node:internal/modules/helpers',
      function: 'require',
      line: 141,
      method: null,
      native: false
    },
    {
      column: 20,
      file: 'Z:\\Visual_Codes\\rudrax\\backend\\app.js',
      function: null,
      line: 43,
      method: null,
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
2025-07-24 13:18:43 [ERROR] uncaughtException: Unexpected token ','
Z:\Visual_Codes\rudrax\backend\controllers\invoice\index.js:15
   },
    ^

SyntaxError: Unexpected token ','
    at wrapSafe (node:internal/modules/cjs/loader:1469:18)
    at Module._compile (node:internal/modules/cjs/loader:1491:20)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\routers\invoiceApi.js:4:27)
Z:\Visual_Codes\rudrax\backend\controllers\invoice\index.js:15
   },
    ^

SyntaxError: Unexpected token ','
    at wrapSafe (node:internal/modules/cjs/loader:1469:18)
    at Module._compile (node:internal/modules/cjs/loader:1491:20)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\routers\invoiceApi.js:4:27)
{
  error: Z:\Visual_Codes\rudrax\backend\controllers\invoice\index.js:15
     },
      ^
  
  SyntaxError: Unexpected token ','
      at wrapSafe (node:internal/modules/cjs/loader:1469:18)
      at Module._compile (node:internal/modules/cjs/loader:1491:20)
      at Object..js (node:internal/modules/cjs/loader:1689:10)
      at Module.load (node:internal/modules/cjs/loader:1318:32)
      at Function._load (node:internal/modules/cjs/loader:1128:12)
      at TracingChannel.traceSync (node:diagnostics_channel:315:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
      at Module.require (node:internal/modules/cjs/loader:1340:12)
      at require (node:internal/modules/helpers:141:16)
      at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\routers\invoiceApi.js:4:27),
  exception: true,
  date: 'Thu Jul 24 2025 13:18:43 GMT+0530 (India Standard Time)',
  process: {
    pid: 11444,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\rudrax\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\rudrax\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 111751168,
      heapTotal: 68829184,
      heapUsed: 41874680,
      external: 2318335,
      arrayBuffers: 21663
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 3684.171 },
  trace: [
    {
      column: 18,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapSafe',
      line: 1469,
      method: null,
      native: false
    },
    {
      column: 20,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module._compile',
      line: 1491,
      method: '_compile',
      native: false
    },
    {
      column: 10,
      file: 'node:internal/modules/cjs/loader',
      function: 'Object..js',
      line: 1689,
      method: '.js',
      native: false
    },
    {
      column: 32,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.load',
      line: 1318,
      method: 'load',
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Function._load',
      line: 1128,
      method: '_load',
      native: false
    },
    {
      column: 14,
      file: 'node:diagnostics_channel',
      function: 'TracingChannel.traceSync',
      line: 315,
      method: 'traceSync',
      native: false
    },
    {
      column: 24,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapModuleLoad',
      line: 218,
      method: null,
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.require',
      line: 1340,
      method: 'require',
      native: false
    },
    {
      column: 16,
      file: 'node:internal/modules/helpers',
      function: 'require',
      line: 141,
      method: null,
      native: false
    },
    {
      column: 27,
      file: 'Z:\\Visual_Codes\\rudrax\\backend\\routers\\invoiceApi.js',
      function: null,
      line: 4,
      method: null,
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
2025-07-24 13:18:46 [ERROR] uncaughtException: Unexpected token ','
Z:\Visual_Codes\rudrax\backend\controllers\invoice\index.js:15
   },
    ^

SyntaxError: Unexpected token ','
    at wrapSafe (node:internal/modules/cjs/loader:1469:18)
    at Module._compile (node:internal/modules/cjs/loader:1491:20)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\routers\invoiceApi.js:4:27)
Z:\Visual_Codes\rudrax\backend\controllers\invoice\index.js:15
   },
    ^

SyntaxError: Unexpected token ','
    at wrapSafe (node:internal/modules/cjs/loader:1469:18)
    at Module._compile (node:internal/modules/cjs/loader:1491:20)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\routers\invoiceApi.js:4:27)
{
  error: Z:\Visual_Codes\rudrax\backend\controllers\invoice\index.js:15
     },
      ^
  
  SyntaxError: Unexpected token ','
      at wrapSafe (node:internal/modules/cjs/loader:1469:18)
      at Module._compile (node:internal/modules/cjs/loader:1491:20)
      at Object..js (node:internal/modules/cjs/loader:1689:10)
      at Module.load (node:internal/modules/cjs/loader:1318:32)
      at Function._load (node:internal/modules/cjs/loader:1128:12)
      at TracingChannel.traceSync (node:diagnostics_channel:315:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
      at Module.require (node:internal/modules/cjs/loader:1340:12)
      at require (node:internal/modules/helpers:141:16)
      at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\routers\invoiceApi.js:4:27),
  exception: true,
  date: 'Thu Jul 24 2025 13:18:46 GMT+0530 (India Standard Time)',
  process: {
    pid: 11960,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\rudrax\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\rudrax\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 112455680,
      heapTotal: 69296128,
      heapUsed: 42340904,
      external: 2318335,
      arrayBuffers: 21663
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 3686.734 },
  trace: [
    {
      column: 18,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapSafe',
      line: 1469,
      method: null,
      native: false
    },
    {
      column: 20,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module._compile',
      line: 1491,
      method: '_compile',
      native: false
    },
    {
      column: 10,
      file: 'node:internal/modules/cjs/loader',
      function: 'Object..js',
      line: 1689,
      method: '.js',
      native: false
    },
    {
      column: 32,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.load',
      line: 1318,
      method: 'load',
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Function._load',
      line: 1128,
      method: '_load',
      native: false
    },
    {
      column: 14,
      file: 'node:diagnostics_channel',
      function: 'TracingChannel.traceSync',
      line: 315,
      method: 'traceSync',
      native: false
    },
    {
      column: 24,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapModuleLoad',
      line: 218,
      method: null,
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.require',
      line: 1340,
      method: 'require',
      native: false
    },
    {
      column: 16,
      file: 'node:internal/modules/helpers',
      function: 'require',
      line: 141,
      method: null,
      native: false
    },
    {
      column: 27,
      file: 'Z:\\Visual_Codes\\rudrax\\backend\\routers\\invoiceApi.js',
      function: null,
      line: 4,
      method: null,
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
2025-07-24 13:27:31 [ERROR] uncaughtException: Route.get() requires a callback function but got a [object Undefined]
Error: Route.get() requires a callback function but got a [object Undefined]
    at Route.<computed> [as get] (Z:\Visual_Codes\rudrax\backend\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (Z:\Visual_Codes\rudrax\backend\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\routers\invoiceApi.js:6:8)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
Error: Route.get() requires a callback function but got a [object Undefined]
    at Route.<computed> [as get] (Z:\Visual_Codes\rudrax\backend\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (Z:\Visual_Codes\rudrax\backend\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\routers\invoiceApi.js:6:8)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
{
  error: Error: Route.get() requires a callback function but got a [object Undefined]
      at Route.<computed> [as get] (Z:\Visual_Codes\rudrax\backend\node_modules\express\lib\router\route.js:216:15)
      at proto.<computed> [as get] (Z:\Visual_Codes\rudrax\backend\node_modules\express\lib\router\index.js:521:19)
      at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\routers\invoiceApi.js:6:8)
      at Module._compile (node:internal/modules/cjs/loader:1546:14)
      at Object..js (node:internal/modules/cjs/loader:1689:10)
      at Module.load (node:internal/modules/cjs/loader:1318:32)
      at Function._load (node:internal/modules/cjs/loader:1128:12)
      at TracingChannel.traceSync (node:diagnostics_channel:315:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
      at Module.require (node:internal/modules/cjs/loader:1340:12),
  exception: true,
  date: 'Thu Jul 24 2025 13:27:31 GMT+0530 (India Standard Time)',
  process: {
    pid: 9300,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\rudrax\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\rudrax\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 111423488,
      heapTotal: 68362240,
      heapUsed: 41860864,
      external: 2318335,
      arrayBuffers: 21663
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 4212.359 },
  trace: [
    {
      column: 15,
      file: 'Z:\\Visual_Codes\\rudrax\\backend\\node_modules\\express\\lib\\router\\route.js',
      function: 'Route.<computed> [as get]',
      line: 216,
      method: '<computed> [as get]',
      native: false
    },
    {
      column: 19,
      file: 'Z:\\Visual_Codes\\rudrax\\backend\\node_modules\\express\\lib\\router\\index.js',
      function: 'proto.<computed> [as get]',
      line: 521,
      method: '<computed> [as get]',
      native: false
    },
    {
      column: 8,
      file: 'Z:\\Visual_Codes\\rudrax\\backend\\routers\\invoiceApi.js',
      function: null,
      line: 6,
      method: null,
      native: false
    },
    {
      column: 14,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module._compile',
      line: 1546,
      method: '_compile',
      native: false
    },
    {
      column: 10,
      file: 'node:internal/modules/cjs/loader',
      function: 'Object..js',
      line: 1689,
      method: '.js',
      native: false
    },
    {
      column: 32,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.load',
      line: 1318,
      method: 'load',
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Function._load',
      line: 1128,
      method: '_load',
      native: false
    },
    {
      column: 14,
      file: 'node:diagnostics_channel',
      function: 'TracingChannel.traceSync',
      line: 315,
      method: 'traceSync',
      native: false
    },
    {
      column: 24,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapModuleLoad',
      line: 218,
      method: null,
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.require',
      line: 1340,
      method: 'require',
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
2025-07-24 13:37:31 [ERROR] uncaughtException: Route.get() requires a callback function but got a [object Undefined]
Error: Route.get() requires a callback function but got a [object Undefined]
    at Route.<computed> [as get] (Z:\Visual_Codes\rudrax\backend\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (Z:\Visual_Codes\rudrax\backend\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\routers\invoiceApi.js:7:8)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
Error: Route.get() requires a callback function but got a [object Undefined]
    at Route.<computed> [as get] (Z:\Visual_Codes\rudrax\backend\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (Z:\Visual_Codes\rudrax\backend\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\routers\invoiceApi.js:7:8)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
{
  error: Error: Route.get() requires a callback function but got a [object Undefined]
      at Route.<computed> [as get] (Z:\Visual_Codes\rudrax\backend\node_modules\express\lib\router\route.js:216:15)
      at proto.<computed> [as get] (Z:\Visual_Codes\rudrax\backend\node_modules\express\lib\router\index.js:521:19)
      at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\routers\invoiceApi.js:7:8)
      at Module._compile (node:internal/modules/cjs/loader:1546:14)
      at Object..js (node:internal/modules/cjs/loader:1689:10)
      at Module.load (node:internal/modules/cjs/loader:1318:32)
      at Function._load (node:internal/modules/cjs/loader:1128:12)
      at TracingChannel.traceSync (node:diagnostics_channel:315:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
      at Module.require (node:internal/modules/cjs/loader:1340:12),
  exception: true,
  date: 'Thu Jul 24 2025 13:37:31 GMT+0530 (India Standard Time)',
  process: {
    pid: 5688,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\rudrax\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\rudrax\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 111259648,
      heapTotal: 68247552,
      heapUsed: 42234464,
      external: 2318335,
      arrayBuffers: 21663
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 4811.703 },
  trace: [
    {
      column: 15,
      file: 'Z:\\Visual_Codes\\rudrax\\backend\\node_modules\\express\\lib\\router\\route.js',
      function: 'Route.<computed> [as get]',
      line: 216,
      method: '<computed> [as get]',
      native: false
    },
    {
      column: 19,
      file: 'Z:\\Visual_Codes\\rudrax\\backend\\node_modules\\express\\lib\\router\\index.js',
      function: 'proto.<computed> [as get]',
      line: 521,
      method: '<computed> [as get]',
      native: false
    },
    {
      column: 8,
      file: 'Z:\\Visual_Codes\\rudrax\\backend\\routers\\invoiceApi.js',
      function: null,
      line: 7,
      method: null,
      native: false
    },
    {
      column: 14,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module._compile',
      line: 1546,
      method: '_compile',
      native: false
    },
    {
      column: 10,
      file: 'node:internal/modules/cjs/loader',
      function: 'Object..js',
      line: 1689,
      method: '.js',
      native: false
    },
    {
      column: 32,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.load',
      line: 1318,
      method: 'load',
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Function._load',
      line: 1128,
      method: '_load',
      native: false
    },
    {
      column: 14,
      file: 'node:diagnostics_channel',
      function: 'TracingChannel.traceSync',
      line: 315,
      method: 'traceSync',
      native: false
    },
    {
      column: 24,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapModuleLoad',
      line: 218,
      method: null,
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.require',
      line: 1340,
      method: 'require',
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
2025-07-24 13:52:42 [ERROR] uncaughtException: router.Post is not a function
TypeError: router.Post is not a function
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\routers\invoiceApi.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:40:27)
TypeError: router.Post is not a function
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\routers\invoiceApi.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:40:27)
{
  error: TypeError: router.Post is not a function
      at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\routers\invoiceApi.js:8:8)
      at Module._compile (node:internal/modules/cjs/loader:1546:14)
      at Object..js (node:internal/modules/cjs/loader:1689:10)
      at Module.load (node:internal/modules/cjs/loader:1318:32)
      at Function._load (node:internal/modules/cjs/loader:1128:12)
      at TracingChannel.traceSync (node:diagnostics_channel:315:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
      at Module.require (node:internal/modules/cjs/loader:1340:12)
      at require (node:internal/modules/helpers:141:16)
      at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:40:27),
  exception: true,
  date: 'Thu Jul 24 2025 13:52:42 GMT+0530 (India Standard Time)',
  process: {
    pid: 6796,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\rudrax\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\rudrax\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 110907392,
      heapTotal: 68100096,
      heapUsed: 41517920,
      external: 2318335,
      arrayBuffers: 21663
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 5722.906 },
  trace: [
    {
      column: 8,
      file: 'Z:\\Visual_Codes\\rudrax\\backend\\routers\\invoiceApi.js',
      function: null,
      line: 8,
      method: null,
      native: false
    },
    {
      column: 14,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module._compile',
      line: 1546,
      method: '_compile',
      native: false
    },
    {
      column: 10,
      file: 'node:internal/modules/cjs/loader',
      function: 'Object..js',
      line: 1689,
      method: '.js',
      native: false
    },
    {
      column: 32,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.load',
      line: 1318,
      method: 'load',
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Function._load',
      line: 1128,
      method: '_load',
      native: false
    },
    {
      column: 14,
      file: 'node:diagnostics_channel',
      function: 'TracingChannel.traceSync',
      line: 315,
      method: 'traceSync',
      native: false
    },
    {
      column: 24,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapModuleLoad',
      line: 218,
      method: null,
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.require',
      line: 1340,
      method: 'require',
      native: false
    },
    {
      column: 16,
      file: 'node:internal/modules/helpers',
      function: 'require',
      line: 141,
      method: null,
      native: false
    },
    {
      column: 27,
      file: 'Z:\\Visual_Codes\\rudrax\\backend\\app.js',
      function: null,
      line: 40,
      method: null,
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
2025-07-24 14:02:31 [ERROR] uncaughtException: Unexpected token '.'
Z:\Visual_Codes\rudrax\backend\controllers\invoice\index.js:123
                              , data: updated? {Object.keys:value}:null
                                                      ^

SyntaxError: Unexpected token '.'
    at wrapSafe (node:internal/modules/cjs/loader:1469:18)
    at Module._compile (node:internal/modules/cjs/loader:1491:20)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\routers\invoiceApi.js:4:27)
Z:\Visual_Codes\rudrax\backend\controllers\invoice\index.js:123
                              , data: updated? {Object.keys:value}:null
                                                      ^

SyntaxError: Unexpected token '.'
    at wrapSafe (node:internal/modules/cjs/loader:1469:18)
    at Module._compile (node:internal/modules/cjs/loader:1491:20)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\routers\invoiceApi.js:4:27)
{
  error: Z:\Visual_Codes\rudrax\backend\controllers\invoice\index.js:123
                                , data: updated? {Object.keys:value}:null
                                                        ^
  
  SyntaxError: Unexpected token '.'
      at wrapSafe (node:internal/modules/cjs/loader:1469:18)
      at Module._compile (node:internal/modules/cjs/loader:1491:20)
      at Object..js (node:internal/modules/cjs/loader:1689:10)
      at Module.load (node:internal/modules/cjs/loader:1318:32)
      at Function._load (node:internal/modules/cjs/loader:1128:12)
      at TracingChannel.traceSync (node:diagnostics_channel:315:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
      at Module.require (node:internal/modules/cjs/loader:1340:12)
      at require (node:internal/modules/helpers:141:16)
      at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\routers\invoiceApi.js:4:27),
  exception: true,
  date: 'Thu Jul 24 2025 14:02:31 GMT+0530 (India Standard Time)',
  process: {
    pid: 12604,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\rudrax\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\rudrax\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 111751168,
      heapTotal: 68624384,
      heapUsed: 41868616,
      external: 2318335,
      arrayBuffers: 21663
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 6312.203 },
  trace: [
    {
      column: 18,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapSafe',
      line: 1469,
      method: null,
      native: false
    },
    {
      column: 20,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module._compile',
      line: 1491,
      method: '_compile',
      native: false
    },
    {
      column: 10,
      file: 'node:internal/modules/cjs/loader',
      function: 'Object..js',
      line: 1689,
      method: '.js',
      native: false
    },
    {
      column: 32,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.load',
      line: 1318,
      method: 'load',
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Function._load',
      line: 1128,
      method: '_load',
      native: false
    },
    {
      column: 14,
      file: 'node:diagnostics_channel',
      function: 'TracingChannel.traceSync',
      line: 315,
      method: 'traceSync',
      native: false
    },
    {
      column: 24,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapModuleLoad',
      line: 218,
      method: null,
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.require',
      line: 1340,
      method: 'require',
      native: false
    },
    {
      column: 16,
      file: 'node:internal/modules/helpers',
      function: 'require',
      line: 141,
      method: null,
      native: false
    },
    {
      column: 27,
      file: 'Z:\\Visual_Codes\\rudrax\\backend\\routers\\invoiceApi.js',
      function: null,
      line: 4,
      method: null,
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
2025-07-24 14:28:32 [ERROR] uncaughtException: Invalid or unexpected token
Z:\Visual_Codes\rudrax\backend\routers\file_managerApi.js:25
"
^

SyntaxError: Invalid or unexpected token
    at wrapSafe (node:internal/modules/cjs/loader:1469:18)
    at Module._compile (node:internal/modules/cjs/loader:1491:20)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:32)
Z:\Visual_Codes\rudrax\backend\routers\file_managerApi.js:25
"
^

SyntaxError: Invalid or unexpected token
    at wrapSafe (node:internal/modules/cjs/loader:1469:18)
    at Module._compile (node:internal/modules/cjs/loader:1491:20)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:32)
{
  error: Z:\Visual_Codes\rudrax\backend\routers\file_managerApi.js:25
  "
  ^
  
  SyntaxError: Invalid or unexpected token
      at wrapSafe (node:internal/modules/cjs/loader:1469:18)
      at Module._compile (node:internal/modules/cjs/loader:1491:20)
      at Object..js (node:internal/modules/cjs/loader:1689:10)
      at Module.load (node:internal/modules/cjs/loader:1318:32)
      at Function._load (node:internal/modules/cjs/loader:1128:12)
      at TracingChannel.traceSync (node:diagnostics_channel:315:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
      at Module.require (node:internal/modules/cjs/loader:1340:12)
      at require (node:internal/modules/helpers:141:16)
      at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:32),
  exception: true,
  date: 'Thu Jul 24 2025 14:28:32 GMT+0530 (India Standard Time)',
  process: {
    pid: 12148,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\rudrax\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\rudrax\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 110915584,
      heapTotal: 68100096,
      heapUsed: 41693968,
      external: 2318335,
      arrayBuffers: 21663
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 7872.687 },
  trace: [
    {
      column: 18,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapSafe',
      line: 1469,
      method: null,
      native: false
    },
    {
      column: 20,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module._compile',
      line: 1491,
      method: '_compile',
      native: false
    },
    {
      column: 10,
      file: 'node:internal/modules/cjs/loader',
      function: 'Object..js',
      line: 1689,
      method: '.js',
      native: false
    },
    {
      column: 32,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.load',
      line: 1318,
      method: 'load',
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Function._load',
      line: 1128,
      method: '_load',
      native: false
    },
    {
      column: 14,
      file: 'node:diagnostics_channel',
      function: 'TracingChannel.traceSync',
      line: 315,
      method: 'traceSync',
      native: false
    },
    {
      column: 24,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapModuleLoad',
      line: 218,
      method: null,
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.require',
      line: 1340,
      method: 'require',
      native: false
    },
    {
      column: 16,
      file: 'node:internal/modules/helpers',
      function: 'require',
      line: 141,
      method: null,
      native: false
    },
    {
      column: 32,
      file: 'Z:\\Visual_Codes\\rudrax\\backend\\app.js',
      function: null,
      line: 43,
      method: null,
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
2025-07-24 14:28:43 [ERROR] uncaughtException: Invalid or unexpected token
Z:\Visual_Codes\rudrax\backend\routers\file_managerApi.js:25
"
^

SyntaxError: Invalid or unexpected token
    at wrapSafe (node:internal/modules/cjs/loader:1469:18)
    at Module._compile (node:internal/modules/cjs/loader:1491:20)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:32)
Z:\Visual_Codes\rudrax\backend\routers\file_managerApi.js:25
"
^

SyntaxError: Invalid or unexpected token
    at wrapSafe (node:internal/modules/cjs/loader:1469:18)
    at Module._compile (node:internal/modules/cjs/loader:1491:20)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:32)
{
  error: Z:\Visual_Codes\rudrax\backend\routers\file_managerApi.js:25
  "
  ^
  
  SyntaxError: Invalid or unexpected token
      at wrapSafe (node:internal/modules/cjs/loader:1469:18)
      at Module._compile (node:internal/modules/cjs/loader:1491:20)
      at Object..js (node:internal/modules/cjs/loader:1689:10)
      at Module.load (node:internal/modules/cjs/loader:1318:32)
      at Function._load (node:internal/modules/cjs/loader:1128:12)
      at TracingChannel.traceSync (node:diagnostics_channel:315:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
      at Module.require (node:internal/modules/cjs/loader:1340:12)
      at require (node:internal/modules/helpers:141:16)
      at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:32),
  exception: true,
  date: 'Thu Jul 24 2025 14:28:43 GMT+0530 (India Standard Time)',
  process: {
    pid: 536,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\rudrax\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\rudrax\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 112431104,
      heapTotal: 69296128,
      heapUsed: 42632496,
      external: 2318335,
      arrayBuffers: 21663
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 7884.421 },
  trace: [
    {
      column: 18,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapSafe',
      line: 1469,
      method: null,
      native: false
    },
    {
      column: 20,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module._compile',
      line: 1491,
      method: '_compile',
      native: false
    },
    {
      column: 10,
      file: 'node:internal/modules/cjs/loader',
      function: 'Object..js',
      line: 1689,
      method: '.js',
      native: false
    },
    {
      column: 32,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.load',
      line: 1318,
      method: 'load',
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Function._load',
      line: 1128,
      method: '_load',
      native: false
    },
    {
      column: 14,
      file: 'node:diagnostics_channel',
      function: 'TracingChannel.traceSync',
      line: 315,
      method: 'traceSync',
      native: false
    },
    {
      column: 24,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapModuleLoad',
      line: 218,
      method: null,
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.require',
      line: 1340,
      method: 'require',
      native: false
    },
    {
      column: 16,
      file: 'node:internal/modules/helpers',
      function: 'require',
      line: 141,
      method: null,
      native: false
    },
    {
      column: 32,
      file: 'Z:\\Visual_Codes\\rudrax\\backend\\app.js',
      function: null,
      line: 43,
      method: null,
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
2025-07-24 14:28:48 [ERROR] uncaughtException: Invalid or unexpected token
Z:\Visual_Codes\rudrax\backend\routers\file_managerApi.js:25
"
^

SyntaxError: Invalid or unexpected token
    at wrapSafe (node:internal/modules/cjs/loader:1469:18)
    at Module._compile (node:internal/modules/cjs/loader:1491:20)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:32)
Z:\Visual_Codes\rudrax\backend\routers\file_managerApi.js:25
"
^

SyntaxError: Invalid or unexpected token
    at wrapSafe (node:internal/modules/cjs/loader:1469:18)
    at Module._compile (node:internal/modules/cjs/loader:1491:20)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:32)
{
  error: Z:\Visual_Codes\rudrax\backend\routers\file_managerApi.js:25
  "
  ^
  
  SyntaxError: Invalid or unexpected token
      at wrapSafe (node:internal/modules/cjs/loader:1469:18)
      at Module._compile (node:internal/modules/cjs/loader:1491:20)
      at Object..js (node:internal/modules/cjs/loader:1689:10)
      at Module.load (node:internal/modules/cjs/loader:1318:32)
      at Function._load (node:internal/modules/cjs/loader:1128:12)
      at TracingChannel.traceSync (node:diagnostics_channel:315:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
      at Module.require (node:internal/modules/cjs/loader:1340:12)
      at require (node:internal/modules/helpers:141:16)
      at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:32),
  exception: true,
  date: 'Thu Jul 24 2025 14:28:48 GMT+0530 (India Standard Time)',
  process: {
    pid: 13436,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\rudrax\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\rudrax\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 111435776,
      heapTotal: 68100096,
      heapUsed: 41692552,
      external: 2318335,
      arrayBuffers: 21663
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 7889.218 },
  trace: [
    {
      column: 18,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapSafe',
      line: 1469,
      method: null,
      native: false
    },
    {
      column: 20,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module._compile',
      line: 1491,
      method: '_compile',
      native: false
    },
    {
      column: 10,
      file: 'node:internal/modules/cjs/loader',
      function: 'Object..js',
      line: 1689,
      method: '.js',
      native: false
    },
    {
      column: 32,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.load',
      line: 1318,
      method: 'load',
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Function._load',
      line: 1128,
      method: '_load',
      native: false
    },
    {
      column: 14,
      file: 'node:diagnostics_channel',
      function: 'TracingChannel.traceSync',
      line: 315,
      method: 'traceSync',
      native: false
    },
    {
      column: 24,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapModuleLoad',
      line: 218,
      method: null,
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.require',
      line: 1340,
      method: 'require',
      native: false
    },
    {
      column: 16,
      file: 'node:internal/modules/helpers',
      function: 'require',
      line: 141,
      method: null,
      native: false
    },
    {
      column: 32,
      file: 'Z:\\Visual_Codes\\rudrax\\backend\\app.js',
      function: null,
      line: 43,
      method: null,
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
2025-07-24 14:29:07 [ERROR] uncaughtException: Invalid or unexpected token
Z:\Visual_Codes\rudrax\backend\routers\file_managerApi.js:24
"
^

SyntaxError: Invalid or unexpected token
    at wrapSafe (node:internal/modules/cjs/loader:1469:18)
    at Module._compile (node:internal/modules/cjs/loader:1491:20)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:32)
Z:\Visual_Codes\rudrax\backend\routers\file_managerApi.js:24
"
^

SyntaxError: Invalid or unexpected token
    at wrapSafe (node:internal/modules/cjs/loader:1469:18)
    at Module._compile (node:internal/modules/cjs/loader:1491:20)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:32)
{
  error: Z:\Visual_Codes\rudrax\backend\routers\file_managerApi.js:24
  "
  ^
  
  SyntaxError: Invalid or unexpected token
      at wrapSafe (node:internal/modules/cjs/loader:1469:18)
      at Module._compile (node:internal/modules/cjs/loader:1491:20)
      at Object..js (node:internal/modules/cjs/loader:1689:10)
      at Module.load (node:internal/modules/cjs/loader:1318:32)
      at Function._load (node:internal/modules/cjs/loader:1128:12)
      at TracingChannel.traceSync (node:diagnostics_channel:315:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
      at Module.require (node:internal/modules/cjs/loader:1340:12)
      at require (node:internal/modules/helpers:141:16)
      at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:32),
  exception: true,
  date: 'Thu Jul 24 2025 14:29:07 GMT+0530 (India Standard Time)',
  process: {
    pid: 13172,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\rudrax\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\rudrax\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 112300032,
      heapTotal: 68829184,
      heapUsed: 42569432,
      external: 2318335,
      arrayBuffers: 21663
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 7908.171 },
  trace: [
    {
      column: 18,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapSafe',
      line: 1469,
      method: null,
      native: false
    },
    {
      column: 20,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module._compile',
      line: 1491,
      method: '_compile',
      native: false
    },
    {
      column: 10,
      file: 'node:internal/modules/cjs/loader',
      function: 'Object..js',
      line: 1689,
      method: '.js',
      native: false
    },
    {
      column: 32,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.load',
      line: 1318,
      method: 'load',
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Function._load',
      line: 1128,
      method: '_load',
      native: false
    },
    {
      column: 14,
      file: 'node:diagnostics_channel',
      function: 'TracingChannel.traceSync',
      line: 315,
      method: 'traceSync',
      native: false
    },
    {
      column: 24,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapModuleLoad',
      line: 218,
      method: null,
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.require',
      line: 1340,
      method: 'require',
      native: false
    },
    {
      column: 16,
      file: 'node:internal/modules/helpers',
      function: 'require',
      line: 141,
      method: null,
      native: false
    },
    {
      column: 32,
      file: 'Z:\\Visual_Codes\\rudrax\\backend\\app.js',
      function: null,
      line: 43,
      method: null,
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
2025-07-24 14:29:25 [ERROR] uncaughtException: Invalid or unexpected token
Z:\Visual_Codes\rudrax\backend\routers\file_managerApi.js:19
"
^

SyntaxError: Invalid or unexpected token
    at wrapSafe (node:internal/modules/cjs/loader:1469:18)
    at Module._compile (node:internal/modules/cjs/loader:1491:20)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:32)
Z:\Visual_Codes\rudrax\backend\routers\file_managerApi.js:19
"
^

SyntaxError: Invalid or unexpected token
    at wrapSafe (node:internal/modules/cjs/loader:1469:18)
    at Module._compile (node:internal/modules/cjs/loader:1491:20)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:32)
{
  error: Z:\Visual_Codes\rudrax\backend\routers\file_managerApi.js:19
  "
  ^
  
  SyntaxError: Invalid or unexpected token
      at wrapSafe (node:internal/modules/cjs/loader:1469:18)
      at Module._compile (node:internal/modules/cjs/loader:1491:20)
      at Object..js (node:internal/modules/cjs/loader:1689:10)
      at Module.load (node:internal/modules/cjs/loader:1318:32)
      at Function._load (node:internal/modules/cjs/loader:1128:12)
      at TracingChannel.traceSync (node:diagnostics_channel:315:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
      at Module.require (node:internal/modules/cjs/loader:1340:12)
      at require (node:internal/modules/helpers:141:16)
      at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:32),
  exception: true,
  date: 'Thu Jul 24 2025 14:29:25 GMT+0530 (India Standard Time)',
  process: {
    pid: 14088,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\rudrax\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\rudrax\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 111730688,
      heapTotal: 68624384,
      heapUsed: 42100320,
      external: 2318335,
      arrayBuffers: 21663
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 7926.062 },
  trace: [
    {
      column: 18,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapSafe',
      line: 1469,
      method: null,
      native: false
    },
    {
      column: 20,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module._compile',
      line: 1491,
      method: '_compile',
      native: false
    },
    {
      column: 10,
      file: 'node:internal/modules/cjs/loader',
      function: 'Object..js',
      line: 1689,
      method: '.js',
      native: false
    },
    {
      column: 32,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.load',
      line: 1318,
      method: 'load',
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Function._load',
      line: 1128,
      method: '_load',
      native: false
    },
    {
      column: 14,
      file: 'node:diagnostics_channel',
      function: 'TracingChannel.traceSync',
      line: 315,
      method: 'traceSync',
      native: false
    },
    {
      column: 24,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapModuleLoad',
      line: 218,
      method: null,
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.require',
      line: 1340,
      method: 'require',
      native: false
    },
    {
      column: 16,
      file: 'node:internal/modules/helpers',
      function: 'require',
      line: 141,
      method: null,
      native: false
    },
    {
      column: 32,
      file: 'Z:\\Visual_Codes\\rudrax\\backend\\app.js',
      function: null,
      line: 43,
      method: null,
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
2025-07-24 14:29:33 [ERROR] uncaughtException: Invalid or unexpected token
Z:\Visual_Codes\rudrax\backend\routers\file_managerApi.js:19
"
^

SyntaxError: Invalid or unexpected token
    at wrapSafe (node:internal/modules/cjs/loader:1469:18)
    at Module._compile (node:internal/modules/cjs/loader:1491:20)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:32)
Z:\Visual_Codes\rudrax\backend\routers\file_managerApi.js:19
"
^

SyntaxError: Invalid or unexpected token
    at wrapSafe (node:internal/modules/cjs/loader:1469:18)
    at Module._compile (node:internal/modules/cjs/loader:1491:20)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:32)
{
  error: Z:\Visual_Codes\rudrax\backend\routers\file_managerApi.js:19
  "
  ^
  
  SyntaxError: Invalid or unexpected token
      at wrapSafe (node:internal/modules/cjs/loader:1469:18)
      at Module._compile (node:internal/modules/cjs/loader:1491:20)
      at Object..js (node:internal/modules/cjs/loader:1689:10)
      at Module.load (node:internal/modules/cjs/loader:1318:32)
      at Function._load (node:internal/modules/cjs/loader:1128:12)
      at TracingChannel.traceSync (node:diagnostics_channel:315:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
      at Module.require (node:internal/modules/cjs/loader:1340:12)
      at require (node:internal/modules/helpers:141:16)
      at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:32),
  exception: true,
  date: 'Thu Jul 24 2025 14:29:33 GMT+0530 (India Standard Time)',
  process: {
    pid: 8740,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\rudrax\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\rudrax\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 111464448,
      heapTotal: 68100096,
      heapUsed: 41563728,
      external: 2318335,
      arrayBuffers: 21663
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 7934.453 },
  trace: [
    {
      column: 18,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapSafe',
      line: 1469,
      method: null,
      native: false
    },
    {
      column: 20,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module._compile',
      line: 1491,
      method: '_compile',
      native: false
    },
    {
      column: 10,
      file: 'node:internal/modules/cjs/loader',
      function: 'Object..js',
      line: 1689,
      method: '.js',
      native: false
    },
    {
      column: 32,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.load',
      line: 1318,
      method: 'load',
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Function._load',
      line: 1128,
      method: '_load',
      native: false
    },
    {
      column: 14,
      file: 'node:diagnostics_channel',
      function: 'TracingChannel.traceSync',
      line: 315,
      method: 'traceSync',
      native: false
    },
    {
      column: 24,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapModuleLoad',
      line: 218,
      method: null,
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.require',
      line: 1340,
      method: 'require',
      native: false
    },
    {
      column: 16,
      file: 'node:internal/modules/helpers',
      function: 'require',
      line: 141,
      method: null,
      native: false
    },
    {
      column: 32,
      file: 'Z:\\Visual_Codes\\rudrax\\backend\\app.js',
      function: null,
      line: 43,
      method: null,
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
2025-07-24 14:29:57 [ERROR] uncaughtException: Invalid or unexpected token
Z:\Visual_Codes\rudrax\backend\routers\file_managerApi.js:19
"
^

SyntaxError: Invalid or unexpected token
    at wrapSafe (node:internal/modules/cjs/loader:1469:18)
    at Module._compile (node:internal/modules/cjs/loader:1491:20)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:32)
Z:\Visual_Codes\rudrax\backend\routers\file_managerApi.js:19
"
^

SyntaxError: Invalid or unexpected token
    at wrapSafe (node:internal/modules/cjs/loader:1469:18)
    at Module._compile (node:internal/modules/cjs/loader:1491:20)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:32)
{
  error: Z:\Visual_Codes\rudrax\backend\routers\file_managerApi.js:19
  "
  ^
  
  SyntaxError: Invalid or unexpected token
      at wrapSafe (node:internal/modules/cjs/loader:1469:18)
      at Module._compile (node:internal/modules/cjs/loader:1491:20)
      at Object..js (node:internal/modules/cjs/loader:1689:10)
      at Module.load (node:internal/modules/cjs/loader:1318:32)
      at Function._load (node:internal/modules/cjs/loader:1128:12)
      at TracingChannel.traceSync (node:diagnostics_channel:315:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
      at Module.require (node:internal/modules/cjs/loader:1340:12)
      at require (node:internal/modules/helpers:141:16)
      at Object.<anonymous> (Z:\Visual_Codes\rudrax\backend\app.js:43:32),
  exception: true,
  date: 'Thu Jul 24 2025 14:29:57 GMT+0530 (India Standard Time)',
  process: {
    pid: 6884,
    uid: null,
    gid: null,
    cwd: 'Z:\\Visual_Codes\\rudrax\\backend',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    version: 'v22.11.0',
    argv: [
      'C:\\Program Files\\nodejs\\node.exe',
      'Z:\\Visual_Codes\\rudrax\\backend\\app.js'
    ],
    memoryUsage: {
      rss: 112041984,
      heapTotal: 68886528,
      heapUsed: 42376128,
      external: 2318335,
      arrayBuffers: 21663
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 7957.687 },
  trace: [
    {
      column: 18,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapSafe',
      line: 1469,
      method: null,
      native: false
    },
    {
      column: 20,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module._compile',
      line: 1491,
      method: '_compile',
      native: false
    },
    {
      column: 10,
      file: 'node:internal/modules/cjs/loader',
      function: 'Object..js',
      line: 1689,
      method: '.js',
      native: false
    },
    {
      column: 32,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.load',
      line: 1318,
      method: 'load',
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Function._load',
      line: 1128,
      method: '_load',
      native: false
    },
    {
      column: 14,
      file: 'node:diagnostics_channel',
      function: 'TracingChannel.traceSync',
      line: 315,
      method: 'traceSync',
      native: false
    },
    {
      column: 24,
      file: 'node:internal/modules/cjs/loader',
      function: 'wrapModuleLoad',
      line: 218,
      method: null,
      native: false
    },
    {
      column: 12,
      file: 'node:internal/modules/cjs/loader',
      function: 'Module.require',
      line: 1340,
      method: 'require',
      native: false
    },
    {
      column: 16,
      file: 'node:internal/modules/helpers',
      function: 'require',
      line: 141,
      method: null,
      native: false
    },
    {
      column: 32,
      file: 'Z:\\Visual_Codes\\rudrax\\backend\\app.js',
      function: null,
      line: 43,
      method: null,
      native: false
    }
  ],
  [Symbol(level)]: 'error'
}
